name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    boom:
        description: TNT go boom
        permission: mcpi.boom
        usage: /<command>
        permission-message: NO BOOM FOR YOU!

permissions: {}
